//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment5_Group96.ClubServiceProxy {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="tmpUri", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="tmpUri", ConfigurationName="ClubServiceProxy.ClubServiceSoap")]
    public interface ClubServiceSoap {
        
        // CODEGEN: Generating message contract since element name GetClubsResult from namespace tmpUri is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="tmpUri/GetClubs", ReplyAction="*")]
        Assignment5_Group96.ClubServiceProxy.GetClubsResponse GetClubs(Assignment5_Group96.ClubServiceProxy.GetClubsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="tmpUri/GetClubs", ReplyAction="*")]
        System.Threading.Tasks.Task<Assignment5_Group96.ClubServiceProxy.GetClubsResponse> GetClubsAsync(Assignment5_Group96.ClubServiceProxy.GetClubsRequest request);
        
        // CODEGEN: Generating message contract since element name ClubName from namespace tmpUri is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="tmpUri/getClubInfo", ReplyAction="*")]
        Assignment5_Group96.ClubServiceProxy.getClubInfoResponse getClubInfo(Assignment5_Group96.ClubServiceProxy.getClubInfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="tmpUri/getClubInfo", ReplyAction="*")]
        System.Threading.Tasks.Task<Assignment5_Group96.ClubServiceProxy.getClubInfoResponse> getClubInfoAsync(Assignment5_Group96.ClubServiceProxy.getClubInfoRequest request);
        
        // CODEGEN: Generating message contract since element name ClubName from namespace tmpUri is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="tmpUri/getClubMembers", ReplyAction="*")]
        Assignment5_Group96.ClubServiceProxy.getClubMembersResponse getClubMembers(Assignment5_Group96.ClubServiceProxy.getClubMembersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="tmpUri/getClubMembers", ReplyAction="*")]
        System.Threading.Tasks.Task<Assignment5_Group96.ClubServiceProxy.getClubMembersResponse> getClubMembersAsync(Assignment5_Group96.ClubServiceProxy.getClubMembersRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetClubsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetClubs", Namespace="tmpUri", Order=0)]
        public Assignment5_Group96.ClubServiceProxy.GetClubsRequestBody Body;
        
        public GetClubsRequest() {
        }
        
        public GetClubsRequest(Assignment5_Group96.ClubServiceProxy.GetClubsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetClubsRequestBody {
        
        public GetClubsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetClubsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetClubsResponse", Namespace="tmpUri", Order=0)]
        public Assignment5_Group96.ClubServiceProxy.GetClubsResponseBody Body;
        
        public GetClubsResponse() {
        }
        
        public GetClubsResponse(Assignment5_Group96.ClubServiceProxy.GetClubsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="tmpUri")]
    public partial class GetClubsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Assignment5_Group96.ClubServiceProxy.ArrayOfString GetClubsResult;
        
        public GetClubsResponseBody() {
        }
        
        public GetClubsResponseBody(Assignment5_Group96.ClubServiceProxy.ArrayOfString GetClubsResult) {
            this.GetClubsResult = GetClubsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getClubInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getClubInfo", Namespace="tmpUri", Order=0)]
        public Assignment5_Group96.ClubServiceProxy.getClubInfoRequestBody Body;
        
        public getClubInfoRequest() {
        }
        
        public getClubInfoRequest(Assignment5_Group96.ClubServiceProxy.getClubInfoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="tmpUri")]
    public partial class getClubInfoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ClubName;
        
        public getClubInfoRequestBody() {
        }
        
        public getClubInfoRequestBody(string ClubName) {
            this.ClubName = ClubName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getClubInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getClubInfoResponse", Namespace="tmpUri", Order=0)]
        public Assignment5_Group96.ClubServiceProxy.getClubInfoResponseBody Body;
        
        public getClubInfoResponse() {
        }
        
        public getClubInfoResponse(Assignment5_Group96.ClubServiceProxy.getClubInfoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="tmpUri")]
    public partial class getClubInfoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getClubInfoResult;
        
        public getClubInfoResponseBody() {
        }
        
        public getClubInfoResponseBody(string getClubInfoResult) {
            this.getClubInfoResult = getClubInfoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getClubMembersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getClubMembers", Namespace="tmpUri", Order=0)]
        public Assignment5_Group96.ClubServiceProxy.getClubMembersRequestBody Body;
        
        public getClubMembersRequest() {
        }
        
        public getClubMembersRequest(Assignment5_Group96.ClubServiceProxy.getClubMembersRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="tmpUri")]
    public partial class getClubMembersRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ClubName;
        
        public getClubMembersRequestBody() {
        }
        
        public getClubMembersRequestBody(string ClubName) {
            this.ClubName = ClubName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getClubMembersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getClubMembersResponse", Namespace="tmpUri", Order=0)]
        public Assignment5_Group96.ClubServiceProxy.getClubMembersResponseBody Body;
        
        public getClubMembersResponse() {
        }
        
        public getClubMembersResponse(Assignment5_Group96.ClubServiceProxy.getClubMembersResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="tmpUri")]
    public partial class getClubMembersResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int getClubMembersResult;
        
        public getClubMembersResponseBody() {
        }
        
        public getClubMembersResponseBody(int getClubMembersResult) {
            this.getClubMembersResult = getClubMembersResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ClubServiceSoapChannel : Assignment5_Group96.ClubServiceProxy.ClubServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ClubServiceSoapClient : System.ServiceModel.ClientBase<Assignment5_Group96.ClubServiceProxy.ClubServiceSoap>, Assignment5_Group96.ClubServiceProxy.ClubServiceSoap {
        
        public ClubServiceSoapClient() {
        }
        
        public ClubServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ClubServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClubServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClubServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Assignment5_Group96.ClubServiceProxy.GetClubsResponse Assignment5_Group96.ClubServiceProxy.ClubServiceSoap.GetClubs(Assignment5_Group96.ClubServiceProxy.GetClubsRequest request) {
            return base.Channel.GetClubs(request);
        }
        
        public Assignment5_Group96.ClubServiceProxy.ArrayOfString GetClubs() {
            Assignment5_Group96.ClubServiceProxy.GetClubsRequest inValue = new Assignment5_Group96.ClubServiceProxy.GetClubsRequest();
            inValue.Body = new Assignment5_Group96.ClubServiceProxy.GetClubsRequestBody();
            Assignment5_Group96.ClubServiceProxy.GetClubsResponse retVal = ((Assignment5_Group96.ClubServiceProxy.ClubServiceSoap)(this)).GetClubs(inValue);
            return retVal.Body.GetClubsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Assignment5_Group96.ClubServiceProxy.GetClubsResponse> Assignment5_Group96.ClubServiceProxy.ClubServiceSoap.GetClubsAsync(Assignment5_Group96.ClubServiceProxy.GetClubsRequest request) {
            return base.Channel.GetClubsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Assignment5_Group96.ClubServiceProxy.GetClubsResponse> GetClubsAsync() {
            Assignment5_Group96.ClubServiceProxy.GetClubsRequest inValue = new Assignment5_Group96.ClubServiceProxy.GetClubsRequest();
            inValue.Body = new Assignment5_Group96.ClubServiceProxy.GetClubsRequestBody();
            return ((Assignment5_Group96.ClubServiceProxy.ClubServiceSoap)(this)).GetClubsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Assignment5_Group96.ClubServiceProxy.getClubInfoResponse Assignment5_Group96.ClubServiceProxy.ClubServiceSoap.getClubInfo(Assignment5_Group96.ClubServiceProxy.getClubInfoRequest request) {
            return base.Channel.getClubInfo(request);
        }
        
        public string getClubInfo(string ClubName) {
            Assignment5_Group96.ClubServiceProxy.getClubInfoRequest inValue = new Assignment5_Group96.ClubServiceProxy.getClubInfoRequest();
            inValue.Body = new Assignment5_Group96.ClubServiceProxy.getClubInfoRequestBody();
            inValue.Body.ClubName = ClubName;
            Assignment5_Group96.ClubServiceProxy.getClubInfoResponse retVal = ((Assignment5_Group96.ClubServiceProxy.ClubServiceSoap)(this)).getClubInfo(inValue);
            return retVal.Body.getClubInfoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Assignment5_Group96.ClubServiceProxy.getClubInfoResponse> Assignment5_Group96.ClubServiceProxy.ClubServiceSoap.getClubInfoAsync(Assignment5_Group96.ClubServiceProxy.getClubInfoRequest request) {
            return base.Channel.getClubInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<Assignment5_Group96.ClubServiceProxy.getClubInfoResponse> getClubInfoAsync(string ClubName) {
            Assignment5_Group96.ClubServiceProxy.getClubInfoRequest inValue = new Assignment5_Group96.ClubServiceProxy.getClubInfoRequest();
            inValue.Body = new Assignment5_Group96.ClubServiceProxy.getClubInfoRequestBody();
            inValue.Body.ClubName = ClubName;
            return ((Assignment5_Group96.ClubServiceProxy.ClubServiceSoap)(this)).getClubInfoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Assignment5_Group96.ClubServiceProxy.getClubMembersResponse Assignment5_Group96.ClubServiceProxy.ClubServiceSoap.getClubMembers(Assignment5_Group96.ClubServiceProxy.getClubMembersRequest request) {
            return base.Channel.getClubMembers(request);
        }
        
        public int getClubMembers(string ClubName) {
            Assignment5_Group96.ClubServiceProxy.getClubMembersRequest inValue = new Assignment5_Group96.ClubServiceProxy.getClubMembersRequest();
            inValue.Body = new Assignment5_Group96.ClubServiceProxy.getClubMembersRequestBody();
            inValue.Body.ClubName = ClubName;
            Assignment5_Group96.ClubServiceProxy.getClubMembersResponse retVal = ((Assignment5_Group96.ClubServiceProxy.ClubServiceSoap)(this)).getClubMembers(inValue);
            return retVal.Body.getClubMembersResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Assignment5_Group96.ClubServiceProxy.getClubMembersResponse> Assignment5_Group96.ClubServiceProxy.ClubServiceSoap.getClubMembersAsync(Assignment5_Group96.ClubServiceProxy.getClubMembersRequest request) {
            return base.Channel.getClubMembersAsync(request);
        }
        
        public System.Threading.Tasks.Task<Assignment5_Group96.ClubServiceProxy.getClubMembersResponse> getClubMembersAsync(string ClubName) {
            Assignment5_Group96.ClubServiceProxy.getClubMembersRequest inValue = new Assignment5_Group96.ClubServiceProxy.getClubMembersRequest();
            inValue.Body = new Assignment5_Group96.ClubServiceProxy.getClubMembersRequestBody();
            inValue.Body.ClubName = ClubName;
            return ((Assignment5_Group96.ClubServiceProxy.ClubServiceSoap)(this)).getClubMembersAsync(inValue);
        }
    }
}
